version: "3.9"
services: 
    default:
        build: .
        ports: 
            - "22:22"
        environment: 
            HOSTHOME: $HOME
        volumes:
            - $HOME:/host/$HOME
